language: java
jdk: openjdk11
before_script:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
script:
  - ./mvnw --settings .maven.xml clean deploy -B -U -Dmaven.javadoc.skip=true -Pdeploy